all: KSGuitarSim.cpp StringSound.cpp CircularBuffer.cpp
	g++ -o KSGuitarSim KSGuitarSim.cpp StringSound.cpp CircularBuffer.cpp -lsfml-audio -lsfml-window -lsfml-system -g

clean:
	rm -f KSGuitarSim *.o

